platform :ios, '7.0'

pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'MBProgressHUD'
pod 'SlackTextViewController'
pod 'SWRevealTableViewCell'
pod 'UITextView+Placeholder'
pod 'DZNEmptyDataSet'